# Generated by Django 4.2 on 2023-05-11 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('added_at', models.DateField(auto_now_add=True)),
                ('last_update', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('face_shape', models.CharField(choices=[('Round', 'Round'), ('Square', 'Square'), ('Triangle', 'Triangle'), ('Oval', 'Oval'), ('Heart', 'Heart')], max_length=10)),
                ('eye_color', models.CharField(choices=[('Amber', 'Amber'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Gray', 'Gray'), ('Green', 'Green'), ('Hazel', 'Hazel'), ('Red', 'Red')], max_length=10)),
                ('skin_color', models.CharField(choices=[('Pale', 'Pale'), ('Fair', 'Fair'), ('Medium', 'Medium'), ('Olive', 'Olive'), ('Brown', 'Brown'), ('Dark', 'Dark')], max_length=10)),
                ('phone_number', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_sname', models.CharField(max_length=100)),
                ('last_sname', models.CharField(max_length=100)),
                ('added', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=100)),
                ('phones_number', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=10)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optic.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optic.category')),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='optic.seller')),
            ],
        ),
    ]
