# Generated by Django 4.2 on 2023-05-11 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optic.client')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordereditems', to='optic.product')),
            ],
        ),
    ]
