# Generated by Django 4.2 on 2023-05-11 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0002_ordereditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemscost', to='optic.product'),
        ),
    ]
