# Generated by Django 4.2 on 2023-05-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0003_ordereditem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='quant',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
