# Generated by Django 4.2 on 2023-05-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0005_alter_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderedItem',
        ),
    ]
