# Generated by Django 4.2 on 2023-05-11 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0007_checkout_checkoutitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optic.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optic.product')),
            ],
        ),
    ]
