# Generated by Django 4.2 on 2023-05-11 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0008_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='i_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='checkoutitems',
            name='i_quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='optic.cart'),
        ),
    ]
