# Generated by Django 4.2 on 2023-05-11 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0009_cart_i_quantity_alter_checkoutitems_i_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='phone_number',
        ),
    ]
