# Generated by Django 4.2 on 2023-05-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0010_remove_checkout_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutitems',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='checkoutitems',
            name='i_quantity',
        ),
        migrations.RemoveField(
            model_name='checkoutitems',
            name='product',
        ),
        migrations.DeleteModel(
            name='Checkout',
        ),
        migrations.DeleteModel(
            name='CheckoutItems',
        ),
    ]
