# Generated by Django 4.2 on 2023-05-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0011_remove_checkoutitems_checkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='codebar',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
