# Generated by Django 4.2 on 2023-05-17 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0012_product_codebar_alter_product_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='codebar',
            new_name='barcode',
        ),
    ]
