# Generated by Django 4.2 on 2023-05-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0013_rename_codebar_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
