# Generated by Django 4.2 on 2023-05-19 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0014_client_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_update',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
