# Generated by Django 4.2 on 2023-05-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0016_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='desc',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
