# Generated by Django 4.2 on 2023-05-19 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0017_cart_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='add_time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
