# Generated by Django 4.2 on 2023-05-19 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0018_product_add_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='add_time',
        ),
    ]
