# Generated by Django 4.2 on 2023-05-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0019_remove_product_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
