# Generated by Django 4.2 on 2023-05-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0021_alter_client_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
