# Generated by Django 4.2.1 on 2023-05-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0023_alter_client_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('Added by a non-admin user', 'Added by a non-admin user'), ('Approved by Admin', 'Approved by Admin')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('Added by a non-admin user', 'Added by a non-admin user'), ('Approved by Admin', 'Approved by Admin')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='added_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='edited_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='added_by',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Added by a non-admin user', 'Added by a non-admin user'), ('Approved by Admin', 'Approved by Admin')], max_length=30, null=True),
        ),
    ]
