# Generated by Django 4.2.1 on 2023-05-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0024_brand_status_category_status_client_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('Added by a non-admin user', 'Added by a non-admin user'), ('Approved by Admin', 'Approved by Admin')], default='Added by a non-admin user', max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('Added by a non-admin user', 'Added by a non-admin user'), ('Approved by Admin', 'Approved by Admin')], default='Added by a non-admin user', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('Added by a non-admin user', 'Added by a non-admin user'), ('Approved by Admin', 'Approved by Admin')], default='Added by a non-admin user', max_length=30),
        ),
    ]
