# Generated by Django 4.2.1 on 2023-06-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0026_alter_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='added_by',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
