# Generated by Django 4.2.1 on 2023-06-05 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0027_seller_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='added_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
