# Generated by Django 4.2.1 on 2023-06-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0028_alter_client_added_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], max_length=10)),
                ('number', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
