# Generated by Django 4.2.1 on 2023-06-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0030_variable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
