# Generated by Django 4.2.1 on 2023-06-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0031_delete_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('last_reset', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Variable',
        ),
    ]
