# Generated by Django 4.2.1 on 2023-06-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0032_dailycounter_delete_variable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='DailyCounter',
        ),
    ]
