# Generated by Django 4.2.1 on 2023-06-17 17:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0033_actioncounter_delete_dailycounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncounter',
            name='date',
            field=models.DateField(null=datetime.date.today),
        ),
    ]
