# Generated by Django 4.2.1 on 2023-06-20 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0034_alter_actioncounter_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=datetime.date.today)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SaleCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=datetime.date.today)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
