# Generated by Django 4.2.1 on 2023-06-20 04:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0035_clientcounter_salecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='updated',
            field=models.DateField(null=datetime.date.today),
            preserve_default=datetime.date.today,
        ),
    ]
