# Generated by Django 4.2.1 on 2023-06-20 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0036_cart_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='updated',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
