# Generated by Django 4.2.1 on 2023-06-20 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0037_alter_cart_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
