# Generated by Django 4.2.1 on 2023-06-20 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0038_product_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='updated',
            field=models.DateField(null=datetime.date.today),
        ),
    ]
