# Generated by Django 4.2.1 on 2023-06-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0039_alter_cart_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salecounter',
            name='count',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
