# Generated by Django 4.2.1 on 2023-06-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0042_remove_cart_total_client_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
