# Generated by Django 4.2.1 on 2023-07-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optic', '0044_remove_client_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ManyToManyField(to='optic.seller'),
        ),
    ]
