from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    #path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('register/', views.register_user, name='register'),
    path('clients/', views.viewclient, name='clients'),
    path('oneclient/<int:pk>', views.one_client, name='oneclient'),
    path('delete_client/<int:pk>', views.delete_client, name='delete_client'),
    path('add_client/', views.add_client, name='add_client'),
    path('edit_client/<int:pk>', views.edit_client, name='edit_client'),
    path('search_client/', views.search_client, name='search_client'),
    path('search_client_date/', views.search_client_date, name='search_client_date'),
    path('search_client_date2/', views.search_client_date2, name='search_client_date2'),    
    path('sellers/', views.viewseller, name='sellers'),
    path('oneseller/<int:pk>', views.one_seller, name='oneseller'),
    path('delete_seller/<int:pk>', views.delete_seller, name='delete_seller'),
    path('add_seller/', views.add_seller, name='add_seller'),
    path('edit_seller/<int:pk>', views.edit_seller, name='edit_seller'),
    path('search_seller/', views.search_seller, name='search_seller'),
    path('products/', views.viewproduct, name='products'),
    path('oneproduct/<int:pk>', views.one_product, name='oneproduct'),
    path('delete_product/<int:pk>', views.delete_product, name='delete_product'),
    path('approve_product/<int:pk>', views.approve_product, name='approve_product'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit_product/<int:pk>', views.edit_product, name='edit_product'),
    path('search_product/', views.search_product, name='search_product'),
    path('search_product_bc/', views.search_product_bc, name='search_product_bc'),
    path('filter_product_br/', views.filter_product_br, name='filter_product_br'),
    path('filter_product_c/', views.filter_product_c, name='filter_product_c'),
    path('cart/<int:pk>', views.cart, name='cart'),
    path('checkout/<int:pk>', views.checkout, name='checkout'),
    path('checkout_pdf/<int:pk>', views.checkout_pdf, name='checkout_pdf'),
    path('brand/', views.brand, name='brand'),
    path('category/', views.category, name='category'),
    path('create-pdf/<int:pk>', views.pdf_report_create, name='create-pdf'),
    path('checkadmin', views.checkadmin, name='checkadmin'),
    path('chart/', views.chart, name='chart'),
]